// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnexefOTchxUR1Gdook2LyIlVwIqC_ig0',
    appId: '1:555409444571:web:a4fdc13d389c73fd9046fe',
    messagingSenderId: '555409444571',
    projectId: 'missingbooknotificationsystem',
    authDomain: 'missingbooknotificationsystem.firebaseapp.com',
    databaseURL: 'https://missingbooknotificationsystem-default-rtdb.firebaseio.com',
    storageBucket: 'missingbooknotificationsystem.appspot.com',
    measurementId: 'G-EJRY91WQK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SkseaHxFWUaX_qTnwCENC6brp-9sXg0',
    appId: '1:555409444571:android:b8b83e0cc052efff9046fe',
    messagingSenderId: '555409444571',
    projectId: 'missingbooknotificationsystem',
    databaseURL: 'https://missingbooknotificationsystem-default-rtdb.firebaseio.com',
    storageBucket: 'missingbooknotificationsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVPsXP_KnQFyUOLu4RUC1kEVaMKbg14rw',
    appId: '1:555409444571:ios:1f3c47ebf45c14719046fe',
    messagingSenderId: '555409444571',
    projectId: 'missingbooknotificationsystem',
    databaseURL: 'https://missingbooknotificationsystem-default-rtdb.firebaseio.com',
    storageBucket: 'missingbooknotificationsystem.appspot.com',
    iosBundleId: 'com.man.vin.manholeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVPsXP_KnQFyUOLu4RUC1kEVaMKbg14rw',
    appId: '1:555409444571:ios:1f3c47ebf45c14719046fe',
    messagingSenderId: '555409444571',
    projectId: 'missingbooknotificationsystem',
    databaseURL: 'https://missingbooknotificationsystem-default-rtdb.firebaseio.com',
    storageBucket: 'missingbooknotificationsystem.appspot.com',
    iosBundleId: 'com.man.vin.manholeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOohpMd-diLJPhLHeHUj5_MHsmG8D1CxE',
    appId: '1:555409444571:web:94dbc1b52ca808999046fe',
    messagingSenderId: '555409444571',
    projectId: 'missingbooknotificationsystem',
    authDomain: 'missingbooknotificationsystem.firebaseapp.com',
    databaseURL: 'https://missingbooknotificationsystem-default-rtdb.firebaseio.com',
    storageBucket: 'missingbooknotificationsystem.appspot.com',
    measurementId: 'G-BHRY71ME41',
  );
}
